# Dockerfile: Defines container specifications to startup and run.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

FROM alpine:3.19.1
RUN apk add --no-cache tftp-hpa supervisor

# Create a directory to store the files:
RUN mkdir -p /tftpshare

RUN mkdir -p /var/log/supervisor /etc/supervisor/conf.d
COPY ./docker/supervisord-TFTP.conf /etc/supervisord.conf

CMD ["supervisord", "-c", "/etc/supervisord.conf"]